services:                         # Lista de serviços (containers) que serão criados

  postgres:                       # Configuração do PostgreSQL(Banco de dados)
    image: 'postgres:15-alpine'   # Imagem oficial do Postgres, versão 15, variante leve "alpine"
    container_name: postgres_crud # Nome fixo do container para facilitar identificação
    environment:                  # Variáveis de ambiente usadas pelo Postgres
      POSTGRES_DB: b_usuario      # Nome do banco que será criado automaticamente
      POSTGRES_USER: user         # Usuário padrão do banco
      POSTGRES_PASSWORD: user     # Senha do usuário
    ports:
      - '5433:5432'               # Mapeia porta externa 5433 e interna 5432 (Postgres)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Volume persistente para dados do banco
    restart: always               # Reinicia o container automaticamente se cair
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U user -d b_usuario"] # Comando de verificação
      interval: 10s               # Frequência do teste
      timeout: 5s                 # Tempo máximo de espera por resposta
      retries: 5                  # Quantas falhas até marcar como "unhealthy"
    deploy:                       # Configuração de recursos
      resources:
        limits:
          memory: 1G              # Limite máximo de memória RAM para o container
          cpus: "0.50"            # Limite de CPU (meio núcleo)

  spring_app:                     # Serviço da aplicação Spring Boot
    build: .                      # Usa o Dockerfile no diretorio atual para construir a imagem
    container_name: cadastro_usuario  # Nome fixo do container da aplicação
    ports:
      - "8081:8080"               # Mapeia porta externa 8081 para interna 8080 (Spring Boot)
    environment:                  # Variáveis de ambiente para configurar a aplicação
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/b_usuario
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_PROFILES_ACTIVE: dev # Define perfil ativo como "dev"
    depends_on:                   # Define dependência: só sobe depois do Postgres estar saudável
      postgres:
        condition: service_healthy
    restart: always               # Reiniciar automaticamente se cair
    deploy:
      resources:
        limits:
          memory: 512M            # Limite de memoria para a aplicação
          cpus: "0.50"            # Limite de CPU ( meio núcleo)

volumes:                          # Declaração de volumes persistentes
  postgres_data:                  # Volume usado pelo banco para guardar dados

